services:
  nuxt-app:
    image: oven/bun:1.1.45-slim
    container_name: substio_ui-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Avoid mounting node_modules to sync local dependencies
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0  # Necessary for Nuxt to bind to all addresses inside Docker
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file watching
    command: sh -c "bun install && bun run dev"  # Use Bun commands instead of npm
