// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { CreateUserOfferOffersPostData, CreateUserOfferOffersPostResponses, CreateUserOfferOffersPostErrors, GetAllRawOffersOffersRawGetData, GetAllRawOffersOffersRawGetResponses, GetAllRawOffersOffersRawGetErrors, CreateRawOfferOffersRawPostData, CreateRawOfferOffersRawPostResponses, CreateRawOfferOffersRawPostErrors, ImportRawOffersOffersImportPostData, ImportRawOffersOffersImportPostResponses, ImportRawOffersOffersImportPostErrors, UpdateOfferOffersOfferUuidPatchData, UpdateOfferOffersOfferUuidPatchResponses, UpdateOfferOffersOfferUuidPatchErrors, GetAllOffersOffersGetData, GetAllOffersOffersGetResponses, GetAllOffersOffersGetErrors, GetRawOfferOffersRawOfferUuidGetData, GetRawOfferOffersRawOfferUuidGetResponses, GetRawOfferOffersRawOfferUuidGetErrors, GetLegalRolesOffersLegalRolesGetData, GetLegalRolesOffersLegalRolesGetResponses, ParseRawOffersParseOfferUuidGetData, ParseRawOffersParseOfferUuidGetResponses, ParseRawOffersParseOfferUuidGetErrors, CreatePlacePlacesPostData, CreatePlacePlacesPostResponses, CreatePlacePlacesPostErrors, CreateCityPlacesCityPostData, CreateCityPlacesCityPostResponses, CreateCityPlacesCityPostErrors, GetFacilitiesPlacesFacilityPlaceNameGetData, GetFacilitiesPlacesFacilityPlaceNameGetResponses, GetFacilitiesPlacesFacilityPlaceNameGetErrors, GetCitiesPlacesFacilityUuidPlaceUuidGetData, GetCitiesPlacesFacilityUuidPlaceUuidGetResponses, GetCitiesPlacesFacilityUuidPlaceUuidGetErrors, GetCitiesPlacesCityUuidCityUuidGetData, GetCitiesPlacesCityUuidCityUuidGetResponses, GetCitiesPlacesCityUuidCityUuidGetErrors, GetCitiesPlacesCityCityNameGetData, GetCitiesPlacesCityCityNameGetResponses, GetCitiesPlacesCityCityNameGetErrors, ReadRootGetData, ReadRootGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create User Offer
 */
export const createUserOfferOffersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserOfferOffersPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateUserOfferOffersPostResponses, CreateUserOfferOffersPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All Raw Offers
 */
export const getAllRawOffersOffersRawGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllRawOffersOffersRawGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllRawOffersOffersRawGetResponses, GetAllRawOffersOffersRawGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/raw',
        ...options
    });
};

/**
 * Create Raw Offer
 */
export const createRawOfferOffersRawPost = <ThrowOnError extends boolean = false>(options: Options<CreateRawOfferOffersRawPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateRawOfferOffersRawPostResponses, CreateRawOfferOffersRawPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/raw',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Import Raw Offers
 */
export const importRawOffersOffersImportPost = <ThrowOnError extends boolean = false>(options: Options<ImportRawOffersOffersImportPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ImportRawOffersOffersImportPostResponses, ImportRawOffersOffersImportPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/import',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Update Offer
 */
export const updateOfferOffersOfferUuidPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateOfferOffersOfferUuidPatchData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateOfferOffersOfferUuidPatchResponses, UpdateOfferOffersOfferUuidPatchErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/{offer_uuid}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All Offers
 */
export const getAllOffersOffersGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllOffersOffersGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllOffersOffersGetResponses, GetAllOffersOffersGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/',
        ...options
    });
};

/**
 * Get Raw Offer
 */
export const getRawOfferOffersRawOfferUuidGet = <ThrowOnError extends boolean = false>(options: Options<GetRawOfferOffersRawOfferUuidGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetRawOfferOffersRawOfferUuidGetResponses, GetRawOfferOffersRawOfferUuidGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/raw/{offer_uuid}',
        ...options
    });
};

/**
 * Get Legal Roles
 */
export const getLegalRolesOffersLegalRolesGet = <ThrowOnError extends boolean = false>(options?: Options<GetLegalRolesOffersLegalRolesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetLegalRolesOffersLegalRolesGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/legal_roles',
        ...options
    });
};

/**
 * Parse Raw
 */
export const parseRawOffersParseOfferUuidGet = <ThrowOnError extends boolean = false>(options: Options<ParseRawOffersParseOfferUuidGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ParseRawOffersParseOfferUuidGetResponses, ParseRawOffersParseOfferUuidGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/offers/parse/{offer_uuid}',
        ...options
    });
};

/**
 * Create Place
 */
export const createPlacePlacesPost = <ThrowOnError extends boolean = false>(options: Options<CreatePlacePlacesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreatePlacePlacesPostResponses, CreatePlacePlacesPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create City
 */
export const createCityPlacesCityPost = <ThrowOnError extends boolean = false>(options: Options<CreateCityPlacesCityPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCityPlacesCityPostResponses, CreateCityPlacesCityPostErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/city',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Facilities
 */
export const getFacilitiesPlacesFacilityPlaceNameGet = <ThrowOnError extends boolean = false>(options: Options<GetFacilitiesPlacesFacilityPlaceNameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetFacilitiesPlacesFacilityPlaceNameGetResponses, GetFacilitiesPlacesFacilityPlaceNameGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/facility/{place_name}',
        ...options
    });
};

/**
 * Get Cities
 */
export const getCitiesPlacesFacilityUuidPlaceUuidGet = <ThrowOnError extends boolean = false>(options: Options<GetCitiesPlacesFacilityUuidPlaceUuidGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCitiesPlacesFacilityUuidPlaceUuidGetResponses, GetCitiesPlacesFacilityUuidPlaceUuidGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/facility/uuid/{place_uuid}',
        ...options
    });
};

/**
 * Get Cities
 */
export const getCitiesPlacesCityUuidCityUuidGet = <ThrowOnError extends boolean = false>(options: Options<GetCitiesPlacesCityUuidCityUuidGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCitiesPlacesCityUuidCityUuidGetResponses, GetCitiesPlacesCityUuidCityUuidGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/city/uuid/{city_uuid}',
        ...options
    });
};

/**
 * Get Cities
 */
export const getCitiesPlacesCityCityNameGet = <ThrowOnError extends boolean = false>(options: Options<GetCitiesPlacesCityCityNameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCitiesPlacesCityCityNameGetResponses, GetCitiesPlacesCityCityNameGetErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/places/city/{city_name}',
        ...options
    });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReadRootGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/',
        ...options
    });
};

/**
 * Perform a Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/health',
        ...options
    });
};