// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_import_raw_offers_offers_import_post
 */
export type BodyImportRawOffersOffersImportPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CityAdd
 */
export type CityAdd = {
    /**
     * City Name
     */
    city_name: string;
    /**
     * Lat
     */
    lat: number | string;
    /**
     * Lon
     */
    lon: number | string;
    /**
     * Lat Min
     */
    lat_min?: number | string | null;
    /**
     * Lat Max
     */
    lat_max?: number | string | null;
    /**
     * Lon Min
     */
    lon_min?: number | string | null;
    /**
     * Lon Max
     */
    lon_max?: number | string | null;
    /**
     * Population
     */
    population?: number | null;
    /**
     * Importance
     */
    importance?: number | null;
    /**
     * Category
     */
    category: string;
    /**
     * State
     */
    state?: string | null;
    /**
     * Voivodeship Name
     */
    voivodeship_name: string;
    /**
     * Voivodeship Iso
     */
    voivodeship_iso: string;
    /**
     * Teryt Simc
     */
    teryt_simc: string;
};

/**
 * CityIndexResponse
 */
export type CityIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lon
     */
    lon: string | null;
    /**
     * Voivodeship Name
     */
    voivodeship_name: string;
};

/**
 * CityResponse
 */
export type CityResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lon
     */
    lon: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthCheck
 */
export type HealthCheck = {
    /**
     * Status
     */
    status?: string;
};

/**
 * ImportResult
 */
export type ImportResult = {
    /**
     * Total Records
     */
    total_records: number;
    /**
     * Imported Records
     */
    imported_records: number;
    /**
     * Skipped Records
     */
    skipped_records: number;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * LegalRoleIndexResponse
 */
export type LegalRoleIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * OfferAdd
 */
export type OfferAdd = {
    /**
     * Author
     */
    author: string;
    /**
     * Facility Uuid
     */
    facility_uuid?: string | null;
    /**
     * Facility Name
     */
    facility_name?: string | null;
    /**
     * City Uuid
     */
    city_uuid?: string | null;
    /**
     * City Name
     */
    city_name?: string | null;
    /**
     * Place Name
     */
    place_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Hour
     */
    hour?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Invoice
     */
    invoice?: boolean | null;
    status?: OfferStatus | null;
    /**
     * Roles
     */
    roles?: Array<string> | null;
    source: SourceType;
};

/**
 * OfferIndexResponse
 */
export type OfferIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Author
     */
    author: string;
    /**
     * Place Name
     */
    place_name?: string | null;
    /**
     * Description
     */
    description: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Url
     */
    url: string | null;
    place?: PlaceResponse | null;
    city?: CityResponse | null;
    /**
     * Legal Roles
     */
    legal_roles: Array<RolesResponse>;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Hour
     */
    hour?: string | null;
    /**
     * Valid To
     */
    valid_to?: string | null;
};

/**
 * OfferRawAdd
 */
export type OfferRawAdd = {
    /**
     * Raw Data
     */
    raw_data: string;
    /**
     * Author
     */
    author: string;
    /**
     * Author Uid
     */
    author_uid: string;
    /**
     * Offer Uid
     */
    offer_uid: string;
    /**
     * Timestamp
     */
    timestamp: string;
    source: SourceType;
};

/**
 * OfferStatus
 */
export type OfferStatus = 'imported' | 'new' | 'draft' | 'spam' | 'postponed' | 'accepted' | 'rejected' | 'active';

/**
 * OfferUpdate
 */
export type OfferUpdate = {
    /**
     * Facility Uuid
     */
    facility_uuid?: string | null;
    /**
     * Facility Name
     */
    facility_name?: string | null;
    /**
     * City Uuid
     */
    city_uuid?: string | null;
    /**
     * City Name
     */
    city_name?: string | null;
    /**
     * Place Name
     */
    place_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Hour
     */
    hour?: string | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Invoice
     */
    invoice?: boolean | null;
    /**
     * Visible
     */
    visible?: boolean | null;
    status?: OfferStatus | null;
    /**
     * Roles
     */
    roles?: Array<string> | null;
    /**
     * Email Notification
     */
    email_notification?: boolean | null;
};

/**
 * OffersPaginated
 */
export type OffersPaginated = {
    /**
     * Data
     */
    data: Array<OfferIndexResponse>;
    /**
     * Count
     */
    count: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * ParseResponse
 */
export type ParseResponse = {
    /**
     * Success
     */
    success: boolean;
    data?: SubstitutionOffer | null;
    /**
     * Error
     */
    error?: string | null;
    usage?: UsageDetails | null;
};

/**
 * PlaceAdd
 */
export type PlaceAdd = {
    category: PlaceCategory;
    /**
     * Type
     */
    type?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Street
     */
    street?: string | null;
    /**
     * Street Name
     */
    street_name?: string | null;
    /**
     * Street Number
     */
    street_number?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Epuap
     */
    epuap?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Lat
     */
    lat: number | string | null;
    /**
     * Lon
     */
    lon: number | string | null;
    /**
     * Website
     */
    website?: string | null;
};

/**
 * PlaceCategory
 */
export type PlaceCategory = 'prosecutor' | 'court' | 'police' | 'other';

/**
 * PlaceIndexResponse
 */
export type PlaceIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    category: PlaceCategory;
    /**
     * Name
     */
    name: string;
    /**
     * Street Name
     */
    street_name?: string | null;
    /**
     * Street Number
     */
    street_number?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Department
     */
    department?: string | null;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lon
     */
    lon: string | null;
    /**
     * Website
     */
    website?: string | null;
};

/**
 * PlaceResponse
 */
export type PlaceResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: string | null;
    /**
     * Lon
     */
    lon: string | null;
};

/**
 * RawOfferIndexResponse
 */
export type RawOfferIndexResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Author Uid
     */
    author_uid?: string | null;
    /**
     * Offer Uid
     */
    offer_uid: string;
    /**
     * Raw Data
     */
    raw_data?: string | null;
    source: SourceType;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Url
     */
    url: string | null;
    /**
     * Invoice
     */
    invoice?: boolean | null;
    place?: PlaceResponse | null;
    city?: CityResponse | null;
    /**
     * Place Name
     */
    place_name?: string | null;
    /**
     * Legal Roles
     */
    legal_roles: Array<RolesResponse>;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Hour
     */
    hour?: string | null;
    status?: OfferStatus | null;
    /**
     * Added At
     */
    added_at: string;
};

/**
 * RawOffersPaginated
 */
export type RawOffersPaginated = {
    /**
     * Data
     */
    data: Array<RawOfferIndexResponse>;
    /**
     * Count
     */
    count: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * RolesResponse
 */
export type RolesResponse = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Name
     */
    name: string;
};

/**
 * SourceType
 */
export type SourceType = 'bot' | 'user';

/**
 * SubstitutionOffer
 */
export type SubstitutionOffer = {
    /**
     * Location
     */
    location?: 'sąd' | 'policja' | 'prokuratura' | null;
    /**
     * Location Full Name
     */
    location_full_name?: string | null;
    /**
     * Date
     */
    date?: Array<string> | null;
    /**
     * Time
     */
    time?: Array<string> | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Legal Roles
     */
    legal_roles?: Array<'adwokat' | 'radca prawny' | 'aplikant adwokacki' | 'aplikant radcowski'> | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsageDetails
 */
export type UsageDetails = {
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
    /**
     * Elapsed Time
     */
    elapsed_time: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetLegalRolesOffersLegalRolesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/offers/legal_roles';
};

export type GetLegalRolesOffersLegalRolesGetResponses = {
    /**
     * Response Get Legal Roles Offers Legal Roles Get
     * Successful Response
     */
    200: Array<LegalRoleIndexResponse>;
};

export type GetLegalRolesOffersLegalRolesGetResponse = GetLegalRolesOffersLegalRolesGetResponses[keyof GetLegalRolesOffersLegalRolesGetResponses];

export type GetAllOffersOffersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Field
         */
        field?: 'valid_to' | 'created_at';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
        /**
         * Lat
         */
        lat?: number | null;
        /**
         * Lon
         */
        lon?: number | null;
        /**
         * Distance Km
         */
        distance_km?: number | null;
        /**
         * Legal Role Uuids
         */
        legal_role_uuids?: Array<string> | null;
        /**
         * Invoice
         */
        invoice?: boolean | null;
    };
    url: '/offers';
};

export type GetAllOffersOffersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllOffersOffersGetError = GetAllOffersOffersGetErrors[keyof GetAllOffersOffersGetErrors];

export type GetAllOffersOffersGetResponses = {
    /**
     * Successful Response
     */
    200: OffersPaginated;
};

export type GetAllOffersOffersGetResponse = GetAllOffersOffersGetResponses[keyof GetAllOffersOffersGetResponses];

export type CreateUserOfferOffersPostData = {
    body: OfferAdd;
    path?: never;
    query?: never;
    url: '/offers';
};

export type CreateUserOfferOffersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserOfferOffersPostError = CreateUserOfferOffersPostErrors[keyof CreateUserOfferOffersPostErrors];

export type CreateUserOfferOffersPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetAllRawOffersOffersRawGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Status
         */
        status?: OfferStatus | null;
        /**
         * Field
         */
        field?: 'name' | 'created_at';
        /**
         * Order
         */
        order?: 'asc' | 'desc';
    };
    url: '/offers/raw';
};

export type GetAllRawOffersOffersRawGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllRawOffersOffersRawGetError = GetAllRawOffersOffersRawGetErrors[keyof GetAllRawOffersOffersRawGetErrors];

export type GetAllRawOffersOffersRawGetResponses = {
    /**
     * Successful Response
     */
    200: RawOffersPaginated;
};

export type GetAllRawOffersOffersRawGetResponse = GetAllRawOffersOffersRawGetResponses[keyof GetAllRawOffersOffersRawGetResponses];

export type CreateRawOfferOffersRawPostData = {
    body: OfferRawAdd;
    path?: never;
    query?: never;
    url: '/offers/raw';
};

export type CreateRawOfferOffersRawPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRawOfferOffersRawPostError = CreateRawOfferOffersRawPostErrors[keyof CreateRawOfferOffersRawPostErrors];

export type CreateRawOfferOffersRawPostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ImportRawOffersOffersImportPostData = {
    body: BodyImportRawOffersOffersImportPost;
    path?: never;
    query?: never;
    url: '/offers/import';
};

export type ImportRawOffersOffersImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportRawOffersOffersImportPostError = ImportRawOffersOffersImportPostErrors[keyof ImportRawOffersOffersImportPostErrors];

export type ImportRawOffersOffersImportPostResponses = {
    /**
     * Successful Response
     */
    200: ImportResult;
};

export type ImportRawOffersOffersImportPostResponse = ImportRawOffersOffersImportPostResponses[keyof ImportRawOffersOffersImportPostResponses];

export type GetReviewOfferOffersOfferUuidGetData = {
    body?: never;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/{offer_uuid}';
};

export type GetReviewOfferOffersOfferUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReviewOfferOffersOfferUuidGetError = GetReviewOfferOffersOfferUuidGetErrors[keyof GetReviewOfferOffersOfferUuidGetErrors];

export type GetReviewOfferOffersOfferUuidGetResponses = {
    /**
     * Successful Response
     */
    200: OfferIndexResponse;
};

export type GetReviewOfferOffersOfferUuidGetResponse = GetReviewOfferOffersOfferUuidGetResponses[keyof GetReviewOfferOffersOfferUuidGetResponses];

export type UpdateOfferOffersOfferUuidPatchData = {
    body: OfferUpdate;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/{offer_uuid}';
};

export type UpdateOfferOffersOfferUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOfferOffersOfferUuidPatchError = UpdateOfferOffersOfferUuidPatchErrors[keyof UpdateOfferOffersOfferUuidPatchErrors];

export type UpdateOfferOffersOfferUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateOfferOffersOfferUuidPatchResponse = UpdateOfferOffersOfferUuidPatchResponses[keyof UpdateOfferOffersOfferUuidPatchResponses];

export type GetRawOfferOffersRawOfferUuidGetData = {
    body?: never;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/raw/{offer_uuid}';
};

export type GetRawOfferOffersRawOfferUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRawOfferOffersRawOfferUuidGetError = GetRawOfferOffersRawOfferUuidGetErrors[keyof GetRawOfferOffersRawOfferUuidGetErrors];

export type GetRawOfferOffersRawOfferUuidGetResponses = {
    /**
     * Successful Response
     */
    200: RawOfferIndexResponse;
};

export type GetRawOfferOffersRawOfferUuidGetResponse = GetRawOfferOffersRawOfferUuidGetResponses[keyof GetRawOfferOffersRawOfferUuidGetResponses];

export type AcceptOfferOffersAcceptOfferUuidPatchData = {
    body?: never;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/accept/{offer_uuid}';
};

export type AcceptOfferOffersAcceptOfferUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptOfferOffersAcceptOfferUuidPatchError = AcceptOfferOffersAcceptOfferUuidPatchErrors[keyof AcceptOfferOffersAcceptOfferUuidPatchErrors];

export type AcceptOfferOffersAcceptOfferUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AcceptOfferOffersAcceptOfferUuidPatchResponse = AcceptOfferOffersAcceptOfferUuidPatchResponses[keyof AcceptOfferOffersAcceptOfferUuidPatchResponses];

export type RejectOfferOffersRejectOfferUuidPatchData = {
    body?: never;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/reject/{offer_uuid}';
};

export type RejectOfferOffersRejectOfferUuidPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectOfferOffersRejectOfferUuidPatchError = RejectOfferOffersRejectOfferUuidPatchErrors[keyof RejectOfferOffersRejectOfferUuidPatchErrors];

export type RejectOfferOffersRejectOfferUuidPatchResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RejectOfferOffersRejectOfferUuidPatchResponse = RejectOfferOffersRejectOfferUuidPatchResponses[keyof RejectOfferOffersRejectOfferUuidPatchResponses];

export type ParseRawOffersParseOfferUuidGetData = {
    body?: never;
    path: {
        /**
         * Offer Uuid
         */
        offer_uuid: string;
    };
    query?: never;
    url: '/offers/parse/{offer_uuid}';
};

export type ParseRawOffersParseOfferUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseRawOffersParseOfferUuidGetError = ParseRawOffersParseOfferUuidGetErrors[keyof ParseRawOffersParseOfferUuidGetErrors];

export type ParseRawOffersParseOfferUuidGetResponses = {
    /**
     * Successful Response
     */
    200: ParseResponse;
};

export type ParseRawOffersParseOfferUuidGetResponse = ParseRawOffersParseOfferUuidGetResponses[keyof ParseRawOffersParseOfferUuidGetResponses];

export type CreatePlacePlacesPostData = {
    body: PlaceAdd;
    path?: never;
    query?: never;
    url: '/places/';
};

export type CreatePlacePlacesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePlacePlacesPostError = CreatePlacePlacesPostErrors[keyof CreatePlacePlacesPostErrors];

export type CreatePlacePlacesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateCityPlacesCityPostData = {
    body: CityAdd;
    path?: never;
    query?: never;
    url: '/places/city';
};

export type CreateCityPlacesCityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCityPlacesCityPostError = CreateCityPlacesCityPostErrors[keyof CreateCityPlacesCityPostErrors];

export type CreateCityPlacesCityPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFacilitiesPlacesFacilityPlaceNameGetData = {
    body?: never;
    path: {
        /**
         * Place Name
         */
        place_name: string;
    };
    query?: {
        /**
         * Place Type
         */
        place_type?: string | null;
    };
    url: '/places/facility/{place_name}';
};

export type GetFacilitiesPlacesFacilityPlaceNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFacilitiesPlacesFacilityPlaceNameGetError = GetFacilitiesPlacesFacilityPlaceNameGetErrors[keyof GetFacilitiesPlacesFacilityPlaceNameGetErrors];

export type GetFacilitiesPlacesFacilityPlaceNameGetResponses = {
    /**
     * Response Get Facilities Places Facility  Place Name  Get
     * Successful Response
     */
    200: Array<PlaceIndexResponse>;
};

export type GetFacilitiesPlacesFacilityPlaceNameGetResponse = GetFacilitiesPlacesFacilityPlaceNameGetResponses[keyof GetFacilitiesPlacesFacilityPlaceNameGetResponses];

export type GetFacilityPlacesFacilityUuidPlaceUuidGetData = {
    body?: never;
    path: {
        /**
         * Place Uuid
         */
        place_uuid: string;
    };
    query?: never;
    url: '/places/facility/uuid/{place_uuid}';
};

export type GetFacilityPlacesFacilityUuidPlaceUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFacilityPlacesFacilityUuidPlaceUuidGetError = GetFacilityPlacesFacilityUuidPlaceUuidGetErrors[keyof GetFacilityPlacesFacilityUuidPlaceUuidGetErrors];

export type GetFacilityPlacesFacilityUuidPlaceUuidGetResponses = {
    /**
     * Successful Response
     */
    200: PlaceIndexResponse;
};

export type GetFacilityPlacesFacilityUuidPlaceUuidGetResponse = GetFacilityPlacesFacilityUuidPlaceUuidGetResponses[keyof GetFacilityPlacesFacilityUuidPlaceUuidGetResponses];

export type GetCityPlacesCityUuidCityUuidGetData = {
    body?: never;
    path: {
        /**
         * City Uuid
         */
        city_uuid: string;
    };
    query?: never;
    url: '/places/city/uuid/{city_uuid}';
};

export type GetCityPlacesCityUuidCityUuidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCityPlacesCityUuidCityUuidGetError = GetCityPlacesCityUuidCityUuidGetErrors[keyof GetCityPlacesCityUuidCityUuidGetErrors];

export type GetCityPlacesCityUuidCityUuidGetResponses = {
    /**
     * Successful Response
     */
    200: CityIndexResponse;
};

export type GetCityPlacesCityUuidCityUuidGetResponse = GetCityPlacesCityUuidCityUuidGetResponses[keyof GetCityPlacesCityUuidCityUuidGetResponses];

export type GetCitiesPlacesCityCityNameGetData = {
    body?: never;
    path: {
        /**
         * City Name
         */
        city_name: string;
    };
    query?: never;
    url: '/places/city/{city_name}';
};

export type GetCitiesPlacesCityCityNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCitiesPlacesCityCityNameGetError = GetCitiesPlacesCityCityNameGetErrors[keyof GetCitiesPlacesCityCityNameGetErrors];

export type GetCitiesPlacesCityCityNameGetResponses = {
    /**
     * Response Get Cities Places City  City Name  Get
     * Successful Response
     */
    200: Array<CityIndexResponse>;
};

export type GetCitiesPlacesCityCityNameGetResponse = GetCitiesPlacesCityCityNameGetResponses[keyof GetCitiesPlacesCityCityNameGetResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Return HTTP Status Code 200 (OK)
     */
    200: HealthCheck;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:5000' | (string & {});
};
